/**
 * The QR encoder, checked by reading symbols back rather than by admiring them.
 *
 * A QR encoder has exactly one interesting failure mode: it produces something that looks like a QR
 * code and does not scan. Nothing it asserts about itself catches that — a wrong error-correction
 * table or a wrong interleave is perfectly self-consistent. So this file carries a small *decoder*,
 * written against the standard rather than against `qr-code.ts`, and points it at two things:
 *
 *  1. **Our symbols**, which must read back as the exact payload with every Reed–Solomon syndrome
 *     zero (i.e. not merely correctable — actually clean).
 *  2. **`segno`'s symbols** for the same payloads (`test/fixtures/qr-vectors.json`, generated by
 *     `scripts/qr-fixtures.py`). Decoding another implementation's output with our geometry, block
 *     tables and format bits is what makes the check independent: a mistyped table row cannot pass.
 *
 * What is deliberately NOT asserted is module-for-module equality with segno. Mask selection is a
 * quality heuristic, not a decoding rule — segno, python-qrcode and this encoder all pick different
 * masks for the same payload, and all three decode identically.
 *
 * Belt and braces: `scripts/qr-fixtures.py` additionally feeds our own matrices to `zxing-cpp`, the
 * decoder behind many production scanners, and refuses to write the fixture unless every symbol
 * reads back. The fixture's `verified` field records that run.
 */

import { describe, expect, it } from "vitest";
import fixtures from "./fixtures/qr-vectors.json";
import {
  alignmentPatternPositions,
  blockStructure,
  dataCodewordCapacity,
  encodeQr,
  maskPenalty,
  qrSvgExtent,
  qrToSvgPath,
  rawDataModules,
  smallestVersionFor,
  type QrEccLevel,
} from "@/lib/qr-code";

// ---------------------------------------------------------------------------------------------
// A QR reader, written from the standard. Deliberately strict: it corrects nothing.
// ---------------------------------------------------------------------------------------------

const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x = (x << 1) ^ (x & 0x80 ? 0x11d : 0);
  }
  for (let i = 255; i < 512; i++) GF_EXP[i] = GF_EXP[i - 255];
}

function gfMul(a: number, b: number): number {
  return a === 0 || b === 0 ? 0 : GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

const ECC_BY_FORMAT_BITS: Record<number, QrEccLevel> = { 0: "M", 1: "L", 2: "H", 3: "Q" };

function isFunctionModule(version: number, size: number, x: number, y: number): boolean {
  // Finder patterns with their separators, and the format-information strips beside them.
  if (x <= 8 && y <= 8) return true;
  if (x >= size - 8 && y <= 8) return true;
  if (x <= 8 && y >= size - 8) return true;
  if (x === 6 || y === 6) return true; // timing patterns
  if (version >= 7 && ((x < 6 && y >= size - 11) || (y < 6 && x >= size - 11))) return true;
  const positions = alignmentPatternPositions(version);
  for (const cy of positions) {
    for (const cx of positions) {
      const corner =
        (cx === 6 && cy === 6) ||
        (cx === 6 && cy === size - 7) ||
        (cx === size - 7 && cy === 6);
      if (corner) continue;
      if (Math.abs(x - cx) <= 2 && Math.abs(y - cy) <= 2) return true;
    }
  }
  return false;
}

function maskBit(mask: number, x: number, y: number): boolean {
  switch (mask) {
    case 0: return (x + y) % 2 === 0;
    case 1: return y % 2 === 0;
    case 2: return x % 3 === 0;
    case 3: return (x + y) % 3 === 0;
    case 4: return (Math.floor(x / 3) + Math.floor(y / 2)) % 2 === 0;
    case 5: return ((x * y) % 2) + ((x * y) % 3) === 0;
    case 6: return (((x * y) % 2) + ((x * y) % 3)) % 2 === 0;
    default: return (((x + y) % 2) + ((x * y) % 3)) % 2 === 0;
  }
}

interface DecodedQr {
  text: string;
  version: number;
  ecc: QrEccLevel;
  mask: number;
}

/** Read a symbol back. Throws when the format bits, the syndromes or the mode indicator are wrong. */
function decodeQr(modules: readonly (readonly boolean[])[]): DecodedQr {
  const size = modules.length;
  const version = (size - 17) / 4;
  if (!Number.isInteger(version) || version < 1 || version > 40) {
    throw new Error(`not a QR symbol size: ${size}`);
  }

  // Format information: 15 bits, BCH(15,5) with the standard mask, read from the copy by the
  // top-left finder and required to be intact.
  const formatBits: number[] = [];
  for (let i = 0; i <= 5; i++) formatBits.push(modules[i][8] ? 1 : 0);
  formatBits.push(modules[7][8] ? 1 : 0, modules[8][8] ? 1 : 0, modules[8][7] ? 1 : 0);
  for (let i = 9; i < 15; i++) formatBits.push(modules[8][14 - i] ? 1 : 0);
  let format = 0;
  for (let i = 14; i >= 0; i--) format = (format << 1) | formatBits[i];
  const unmasked = format ^ 0x5412;
  const formatData = (unmasked >>> 10) & 0x1f;
  let rem = formatData;
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  if ((((formatData << 10) | rem) ^ 0x5412) !== format) {
    throw new Error("format information does not check out");
  }
  const ecc = ECC_BY_FORMAT_BITS[(formatData >>> 3) & 3];
  const mask = formatData & 7;

  // Read the data modules in the zigzag, undoing the mask as we go.
  const bits: number[] = [];
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;
    for (let vert = 0; vert < size; vert++) {
      for (let j = 0; j < 2; j++) {
        const x = right - j;
        const upward = ((right + 1) & 2) === 0;
        const y = upward ? size - 1 - vert : vert;
        if (isFunctionModule(version, size, x, y)) continue;
        bits.push((modules[y][x] !== maskBit(mask, x, y) ? 1 : 0));
      }
    }
  }
  const stream: number[] = [];
  for (let i = 0; i + 8 <= bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    stream.push(byte);
  }

  // De-interleave into blocks, then insist every syndrome is zero: the symbol must be undamaged,
  // not merely repairable.
  const { numBlocks, ecPerBlock, numShortBlocks, shortBlockDataLen } = blockStructure(version, ecc);
  const dataLengths = Array.from({ length: numBlocks }, (_, b) =>
    shortBlockDataLen + (b < numShortBlocks ? 0 : 1),
  );
  const dataBlocks: number[][] = dataLengths.map(() => []);
  const eccBlocks: number[][] = dataLengths.map(() => []);
  let cursor = 0;
  for (let i = 0; i <= shortBlockDataLen; i++) {
    for (let b = 0; b < numBlocks; b++) {
      if (i < dataLengths[b]) dataBlocks[b].push(stream[cursor++]);
    }
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (let b = 0; b < numBlocks; b++) eccBlocks[b].push(stream[cursor++]);
  }
  for (let b = 0; b < numBlocks; b++) {
    const codewords = [...dataBlocks[b], ...eccBlocks[b]];
    // QR's generator polynomial has roots α^0 … α^(n−1), so those are the points to evaluate at.
    for (let i = 0; i < ecPerBlock; i++) {
      let syndrome = 0;
      for (const codeword of codewords) syndrome = gfMul(syndrome, GF_EXP[i]) ^ codeword;
      if (syndrome !== 0) throw new Error(`block ${b} fails its Reed–Solomon check`);
    }
  }

  // Byte-mode segment: 4-bit mode indicator, character count, then the payload.
  const dataBits: number[] = [];
  for (const block of dataBlocks) {
    for (const codeword of block) {
      for (let i = 7; i >= 0; i--) dataBits.push((codeword >>> i) & 1);
    }
  }
  const take = (n: number): number => {
    let value = 0;
    for (let i = 0; i < n; i++) value = (value << 1) | (dataBits.shift() as number);
    return value;
  };
  if (take(4) !== 0b0100) throw new Error("not a byte-mode segment");
  const length = take(version <= 9 ? 8 : 16);
  const bytes = new Uint8Array(length);
  for (let i = 0; i < length; i++) bytes[i] = take(8);
  return { text: new TextDecoder().decode(bytes), version, ecc, mask };
}

// ---------------------------------------------------------------------------------------------

function unpack(base64: string, size: number): boolean[][] {
  const bytes = Buffer.from(base64, "base64");
  const modules: boolean[][] = [];
  for (let y = 0; y < size; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < size; x++) {
      const index = y * size + x;
      row.push(((bytes[index >>> 3] >>> (7 - (index & 7))) & 1) !== 0);
    }
    modules.push(row);
  }
  return modules;
}

const vectors = fixtures.vectors as {
  text: string;
  ecc: QrEccLevel;
  version: number;
  size: number;
  modules: string;
  rows?: string[];
}[];

describe("symbols read back", () => {
  it("covers every version and every error-correction level", () => {
    const versions = new Set(vectors.map((v) => v.version));
    for (let version = 1; version <= 40; version++) expect(versions).toContain(version);
    expect(new Set(vectors.map((v) => v.ecc))).toEqual(new Set(["L", "M", "Q", "H"]));
    // The fixture is only worth this much if it was checked by a real scanner when generated.
    expect(fixtures.verified).toContain("zxing-cpp");
  });

  for (const vector of vectors) {
    const label = `v${vector.version}-${vector.ecc}, ${vector.text.length} bytes`;

    it(`decodes our own symbol for ${label}`, () => {
      const qr = encodeQr(vector.text, vector.ecc);
      // Version selection first: a symbol that scans but wastes two versions is still wrong.
      expect(qr.version).toBe(vector.version);
      expect(qr.size).toBe(vector.size);
      const decoded = decodeQr(qr.modules);
      expect(decoded.text).toBe(vector.text);
      expect(decoded.ecc).toBe(vector.ecc);
      expect(decoded.version).toBe(vector.version);
    });

    it(`decodes segno's symbol for ${label} with our tables`, () => {
      // The independent half: another encoder's matrix, read with our geometry and block tables.
      const decoded = decodeQr(unpack(vector.modules, vector.size));
      expect(decoded.text).toBe(vector.text);
      expect(decoded.ecc).toBe(vector.ecc);
      expect(decoded.version).toBe(vector.version);
    });
  }

  it("keeps the readable fixtures consistent with their packed form", () => {
    const readable = vectors.filter((v) => v.rows);
    expect(readable.length).toBeGreaterThan(0);
    for (const vector of readable) {
      const rows = unpack(vector.modules, vector.size).map((row) =>
        row.map((dark) => (dark ? "1" : "0")).join(""),
      );
      expect(rows).toEqual(vector.rows);
    }
  });

  it("refuses a symbol whose modules have been tampered with", () => {
    // The decoder above is only evidence if it can actually fail.
    const qr = encodeQr("wc:topic@2?relay-protocol=irn&symKey=deadbeef", "M");
    const damaged = qr.modules.map((row) => [...row]);
    for (let x = 10; x < 20; x++) damaged[20][x] = !damaged[20][x];
    expect(() => decodeQr(damaged)).toThrow(/Reed–Solomon|byte-mode|format/);
  });
});

describe("capacity tables are internally consistent", () => {
  it("spends every raw codeword on either data or error correction", () => {
    // This is the invariant a mistyped table row breaks: data + ECC must exactly fill the symbol.
    for (let version = 1; version <= 40; version++) {
      for (const ecc of ["L", "M", "Q", "H"] as const) {
        const raw = Math.floor(rawDataModules(version) / 8);
        const { numBlocks, ecPerBlock, numShortBlocks, shortBlockDataLen } = blockStructure(
          version,
          ecc,
        );
        const data = dataCodewordCapacity(version, ecc);
        expect(data).toBe(raw - numBlocks * ecPerBlock);
        expect(numShortBlocks).toBeGreaterThan(0);
        expect(numShortBlocks).toBeLessThanOrEqual(numBlocks);
        // Blocks differ by at most one codeword, and together they account for every one.
        expect(
          numShortBlocks * shortBlockDataLen + (numBlocks - numShortBlocks) * (shortBlockDataLen + 1),
        ).toBe(data);
        if (ecc !== "L") expect(data).toBeLessThanOrEqual(dataCodewordCapacity(version, "L"));
      }
    }
  });

  it("places alignment patterns where the standard's table says", () => {
    // Spot values from ISO/IEC 18004 Table E.1, including version 32's irregular spacing.
    expect(alignmentPatternPositions(1)).toEqual([]);
    expect(alignmentPatternPositions(2)).toEqual([6, 18]);
    expect(alignmentPatternPositions(7)).toEqual([6, 22, 38]);
    expect(alignmentPatternPositions(32)).toEqual([6, 34, 60, 86, 112, 138]);
    expect(alignmentPatternPositions(40)).toEqual([6, 30, 58, 86, 114, 142, 170]);
  });

  it("picks the smallest version that fits, and refuses what cannot", () => {
    expect(smallestVersionFor(1, "M")).toBe(1);
    // Exactly filling version 1 at M (16 data codewords, 2 spent on mode + count) stays at v1.
    expect(smallestVersionFor(14, "M")).toBe(1);
    expect(smallestVersionFor(15, "M")).toBe(2);
    expect(smallestVersionFor(dataCodewordCapacity(40, "L") - 3, "L")).toBe(40);
    expect(smallestVersionFor(dataCodewordCapacity(40, "L") - 2, "L")).toBeNull();
    expect(() => encodeQr("x".repeat(3000), "H")).toThrow(/exceeds QR capacity/);
  });
});

describe("the encoded symbol is structurally a QR code", () => {
  const qr = encodeQr("wc:topic@2?relay-protocol=irn&symKey=deadbeef", "M");

  it("carries the three finder patterns", () => {
    const corners: [number, number][] = [
      [0, 0],
      [qr.size - 7, 0],
      [0, qr.size - 7],
    ];
    for (const [ox, oy] of corners) {
      for (let dy = 0; dy < 7; dy++) {
        for (let dx = 0; dx < 7; dx++) {
          const ring = Math.max(Math.abs(dx - 3), Math.abs(dy - 3));
          expect(qr.modules[oy + dy][ox + dx]).toBe(ring !== 2);
        }
      }
    }
  });

  it("carries the timing patterns and the always-dark module", () => {
    for (let i = 8; i < qr.size - 8; i++) {
      expect(qr.modules[6][i]).toBe(i % 2 === 0);
      expect(qr.modules[i][6]).toBe(i % 2 === 0);
    }
    expect(qr.modules[qr.size - 8][8]).toBe(true);
  });

  it("scores masks by the standard's penalty rules", () => {
    const size = 21;
    const allLight = Array.from({ length: size }, () => new Array<boolean>(size).fill(false));
    // An entirely light symbol trips every rule at once, so its score is nowhere near zero.
    expect(maskPenalty(allLight)).toBeGreaterThan(1000);
    const checkerboard = allLight.map((row, y) => row.map((_, x) => (x + y) % 2 === 0));
    // No runs, no 2×2 blocks, exactly 50% dark.
    expect(maskPenalty(checkerboard)).toBeLessThan(maskPenalty(allLight));
  });
});

describe("SVG output", () => {
  const qr = encodeQr("HELLO", "M");

  it("draws one unit square per dark module inside a quiet zone", () => {
    const path = qrToSvgPath(qr, 4);
    const dark = qr.modules.flat().filter(Boolean).length;
    expect(path.split("M").length - 1).toBe(dark);
    expect(qrSvgExtent(qr, 4)).toBe(qr.size + 8);
    // The top-left finder's corner module sits at the quiet-zone offset, never at 0,0.
    expect(path.startsWith("M4 4h1v1h-1z")).toBe(true);
  });
});
