import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Compiled output of the publishable SDK package (generated by `pnpm sdk:build`).
    "packages/*/dist/**",
    // Agent scratch space: `.claude/worktrees/*` are full git worktrees of this repo, so
    // linting them re-lints (stale copies of) every source file under a second path.
    ".claude/**",
  ]),
]);

export default eslintConfig;
