[[contracts]]
fqn = "hunch_vault::HunchVault"

[[contracts]]
fqn = "market_factory::MarketFactory"

[[contracts]]
fqn = "oracle_registry::OracleRegistry"

[[contracts]]
fqn = "parimutuel_market::ParimutuelMarket"
